export enum BuildingType {
    ADMINISTRATION = 'ADMINISTRATION',
    LIBRARY = 'LIBRARY',
    LECTURE = 'LECTURE',
    RESIDENCE = 'RESIDENCE',
    RESEARCH = 'RESEARCH',
    OFFICES = 'OFFICES',
    DINING = 'DINING',
    SPORTS = 'SPORTS',
    FIRST_AID = 'FIRST_AID',
    PARKING = 'PARKING',
    POST_OFFICE = 'POST_OFFICE',
    WASTE = 'WASTE',
    MISCELLANEOUS = 'MISCELLANEOUS',
    OTHER = 'OTHER',
    NONE = 'NONE'
}
