export enum RoomType {
    OFFICE= 'OFFICE',
    ADMINISTRATION = 'ADMINISTRATION',
    LIBRARY = 'LIBRARY',
    SEMINAR = 'SEMINAR',
    STUDY = 'STUDY',
    LECTURE_HALL = 'LECTURE_HALL',
    FACILITY_MANAGEMENT = 'FACILITY_MANAGEMENT',
    EMERGENCY = 'EMERGENCY',
    TOILET = 'TOILET',
    SERVER_ROOM = 'SERVER_ROOM',
    STORAGE = 'STORAGE',
    MISCELLANEOUS = 'MISCELLANEOUS',
    COMPUTER = 'COMPUTER',
    LAB = 'LAB',
    NONE = 'NONE'
}
